on:
  workflow_dispatch:
    inputs:
      DAY_OF_WEEK:
        type: string
        default: 'today'
      NAME:
        type: string
        required: false
        default: Shyam
      GREETING:
        type: string
        required: false
        default: ''

name: Example Workflow

env:
  FOO: "foo"

jobs:
  check_vars:
    runs-on: ubuntu-latest
    name: Check Vars
    env:
      Greeting: ${{ inputs.GREETING != '' && inputs.GREETING || 'Hello' }}
    steps:
      - name: "Run"
        run: |
          echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
          echo $First_Name
          echo ${{ inputs.NAME }}
          echo "Foo '$FOO' or ${{ env.FOO }}"
        env:
          First_Name: ${{ inputs.NAME }}
    
